project_name: netcp
release:
  github:
    owner: netcp
    name: netcp
  name_template: 'Release {{.Tag}}'
before:
  hooks:
    - go mod download
builds:
  - id: netcp
    binary: netcp
    main: ./cmd/cli/v1
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s
      - -w
      - -X main.GitCommit={{ .ShortCommit }}
      - -X main.BuildDate={{ .Timestamp }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    tags:
      - client
  - id: netcp-srv
    binary: netcp-srv
    main: ./cmd/srv/v1
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s
      - -w
      - -X main.GitCommit={{ .ShortCommit }}
      - -X main.BuildDate={{ .Timestamp }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    tags:
      - server
dockers:
  - id: netcp-srv
    goos: linux
    goarch: amd64
    image_templates:
      - "crashdump/netcp:latest"
      - "crashdump/netcp:{{ .Tag }}"
      - "crashdump/netcp:v{{ .Major }}"
    dockerfile: build/Dockerfile
nfpms:
  - id: netcp
    package_name: netcp
    builds:
      - netcp
    homepage: https://github.com/crashdump/netcp
    maintainer: Adrien Pujol <ap@cdfr.net>
    description:  Copy files and directories across systems without requiring a direct network line-of-sight. Netcp uses a cloud storage endpoint to store the data while in flight.
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    priority: extra
archives:
  - builds:
      - netcp
    name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm: arm
      arm64: arm64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^tests:'