name: build

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud-service-key.json

    steps:
      - uses: actions/checkout@v3

      - run: |
          touch ${GOOGLE_APPLICATION_CREDENTIALS}
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }}" | base64 --decode > ${GOOGLE_APPLICATION_CREDENTIALS}

      # Setup Go & NodeJS
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.2'

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '15'
          check-latest: true

      #
      # Cache
      - uses: actions/cache@v3.0.1
        id: yarn-cache
        with:
          path: |
            ./ui/node_modules
            ~/.config/yarn/global
            ~/.yarn
            ~/go/pkg/mod
          key: ${{ runner.os }}-omnibuild-${{ hashFiles('./go.sum') }}-${{ hashFiles('./ui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-netcpbuild--

      #
      # Build dependencies
      - run: |
          yarn global add @vue/cli @vue/cli-service @vue/cli-service-global @vue/cli-plugin-unit-jest vue-eslint-parser jest
          yarn install

      #
      # Build
      - run: make build

      #
      # Test
      - run: |
          curl -o /usr/local/bin/firebase -L https://firebase.tools/bin/linux/latest
          chmod +rx /usr/local/bin/firebase
          /usr/local/bin/firebase emulators:start --only "auth,database,firestore" &
          sleep 10 # sorry, that's not very pretty.

      - run: make test